### ISSUE TITLE
Using Tilerator in the real world

### ISSUE THREAD

**Issue by leblowl** [kartotherian/tilerator#1]
Hey all, I am not sure this is the best place to post this question, if you know of someone I should rather talk to or somewhere I should rather post this, feel free to let me know.

So I am trying to use tilerator to generate map tiles z=0...15 for a map tile service. I just upgraded my hardware & it seems pretty good for the job. Planet OSM takes around 14 hours to import. Tilerator is chugging away now. It burned through the first 12 zoom levels at lightning speed. It took maybe 4 days to finish z=14, & now it is slowly working on z=15. My question is what does ya'lls production process look like @ wikimaps? How long does it take you guys to generate z=0...15 & what kind of hardware are you using? Also how are updates handled with tilerator? Is there a way to update only tiles that have changed based on OSM planet diffs? @ my current rate, it looks like it will take over two weeks to complete all the tiles... this seems like a big time investment, but I guess if I can update individual tiles over time & never lose my database it isn't too big of a deal as a one time investment. Advice most welcomed. Cheers & thankyou

**Comment by nyurik** [comment]
Hi @leblowl, I only generated tiles for z10+ if they existed in previous zoom. In other words, I used the checkZoom=-1 trick - only generate tile if previous level has a tile.  Usually with slightly older hardware (we have 4 servers), takes a few days to do a full re-gen of z0-16 of existing tiles only  (biggerThan=0). I'm still working on getting the invalidation working, but most of it is already done - the osm2pgsql generates a list of all the invalidated tiles, and i can feed that list into tilerator to add to the job queue.  Please keep me posted of your experience with tilerator. Thanks!

**Comment by leblowl** [comment]
Sweet, thank you, I will try the checkZoom trick. Just to clarify, do ya'll run tilerator across all 4 servers?

**Comment by nyurik** [comment]
At this point, while we are still evaluating how much processing we actually need for tile generation vs rendering, we are running both kartotherian and tilerator on all 4 servers.

**Comment by nyurik** [comment]
@leblowl, btw, if you ever want to chat directly, join our IRC channel -  #wikimedia-discovery @ freenode - see https://www.mediawiki.org/wiki/MediaWiki_on_IRC or https://www.mediawiki.org/wiki/Wikimedia_Discovery#IRC_channel - my nick is "yurik"

**Comment by leblowl** [comment]
perfecto, thank you!
