### ISSUE TITLE
Invalid zoom param - an integer zoom value was expected

### ISSUE THREAD

**Issue by leblowl** [kartotherian/tilerator#2]
Using this command: `curl -X POST 'http://localhost:16533/add?generatorId=gen&storageId=v2&zoom=0&fromZoom=0&beforeZoom=16&checkZoom=-1&parts=12'` to add a job to Tilerator I get an error (message in title). Stack trace says it fails here: https://github.com/kartotherian/kartotherian-core/blob/286670b135433ae4917c72f71157efa28b1284e0/lib/core.js#L408-L411. It appears to be failing on the checkZoom filter param, '-1' doesn't seem to be passing as a valid zoom. Relevant part of stack trace:
```
"stack": "tilerator: Invalid zoom param - an integer zoom value was expected\n 
         at Object.checkType (/usr/local/lib/node_modules/tilerator/node_modules/kartotherian-core/lib/core.js:410:23)\n
         at Job.<anonymous> (/usr/local/lib/node_modules/tilerator/lib/Job.js:96:22)
```

**Comment by leblowl** [comment]
Ok, so I think this error just stems from my misunderstanding of the checkZoom filter. I don't think it makes any sense to use checkZoom=-1 when zoom=0. We can re-open if this isn't the case.

**Comment by nyurik** [comment]
you are right, at zoom=0 it makes no sense to check previous zoom.  I don't think i should make an explicit workaround for this - its better for the caller to figure out the mistake and pass correct params.  Also, I fixed the checkZoom bug https://github.com/kartotherian/tilerator-jobprocessor/commit/a8c1aa198de0d827bab433c3b313a42dbbcf5497
